/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-ajax-data-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';

declare function EtoolsAjaxDataMixin<T extends new (...args: any[]) => {}>(base: T): T & EtoolsAjaxDataMixinConstructor;

interface EtoolsAjaxDataMixinConstructor {
  new(...args: any[]): EtoolsAjaxDataMixin;
}

export {EtoolsAjaxDataMixinConstructor};

interface EtoolsAjaxDataMixin {
  _prepareMultiPartFormData(inputBody: any, prepareMultipartData: any): any;
  _prepareFormData(self: any, body: any, data: any, key: any): any;
  _isFile(data: any): any;
  _isSimpleObject(data: any): any;
}
